import java.awt.Graphics;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class FormDispersaF1 extends javax.swing.JFrame  implements ChangeListener{
    DispersaF1 dispersaF1;
    /** Creates new form FormDispersaF1 */
    public FormDispersaF1() {
        initComponents();
        jScrollPane1.getViewport().addChangeListener(this);
        dispersaF1 = new DispersaF1(6,10);
        dispersaF1.insetarDato(1, 1, 20);
        dispersaF1.insetarDato(2,5, 30);
        dispersaF1.insetarDato(2, 1, 70);
        dispersaF1.insetarDato(5,5, 40);
        dispersaF1.insetarDato(1, 3, 20);
        dispersaF1.insetarDato(2,6, 30);
        dispersaF1.insetarDato(6, 8, 7);
        dispersaF1.insetarDato(5,9, 4);
    }
    public void stateChanged(ChangeEvent g)
    {
        repaint();
    }

    public void paint(Graphics g)
    {
        super.paint(g);
        Graphics g1;
        g1=jScrollPane1.getViewport().getGraphics();
        int posC =100-jScrollPane1.getViewport().getViewPosition().x;
        int posF=50- jScrollPane1.getViewport().getViewPosition().y;
        if( dispersaF1 != null)
        {
            dispersaF1.pintar(g1, posF, posC );
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MATRICES DISPERSAS REPRESENTADAS COMO TRIPLETAS");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 800));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 2000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 800, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jButton1.setText("CREAR DISPERSA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("REDIMENSIONAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("INSERTAR DATO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton3))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String entrada;
        boolean terminado= false;
        int N=0, M =0;
        do
        {
            entrada = JOptionPane.showInputDialog(this,"ingrese el numero de filas de la matriz dispersa [ 1 , 10]");

            if( entrada != null)
            {
                try
                {
                    N = Integer.parseInt(entrada);
                    if( N< 1|| N> 10)
                    {
                        JOptionPane.showMessageDialog(this,"debe ingresar un entero entre [ 1, 10]");
                    }
                    else
                    {
                        terminado = true;
                    }
                }
                catch( NumberFormatException x)
                {
                    JOptionPane.showMessageDialog(this, "la N ingresada debe ser numerica");
                }
            }

        }while ( terminado == false &&  entrada!= null) ;

        do
        {
            entrada = JOptionPane.showInputDialog(this,"ingrese el numero de columnas de la matriz dispersa [ 1 , 10]");

            if( entrada != null)
            {
                try
                {
                    M = Integer.parseInt(entrada);
                    if( M< 1|| M> 10)
                    {
                        JOptionPane.showMessageDialog(this,"debe ingresar un entero entre [ 1, 10]");
                    }
                    else
                    {
                        terminado = true;
                    }
                }
                catch( NumberFormatException x)
                {
                    JOptionPane.showMessageDialog(this, "la M ingresada debe ser numerica");
                }
            }

        }while ( terminado == false &&  entrada!= null) ;


        if(terminado== true)
        {
            dispersaF1= new DispersaF1(N,M);

            repaint();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String entrada;
        boolean terminado= false;
        int cantidad=0;
        do
        {
            entrada = JOptionPane.showInputDialog(this,"ingrese la cantidad a redimensionar [ -3 , 3]");

            if( entrada != null)
            {
                try
                {
                    cantidad = Integer.parseInt(entrada);
                    if( cantidad< -3|| cantidad> 3)
                    {
                        JOptionPane.showMessageDialog(this,"debe ingresar un entero entre [  -3 , 3]");
                    }
                    else
                    {
                        terminado = true;
                    }
                }
                catch( NumberFormatException x)
                {
                    JOptionPane.showMessageDialog(this, "la cantidad ingresada debe ser numerica");
                }
            }

        }while ( terminado == false &&  entrada!= null) ;
        if(terminado== true)
        {
            dispersaF1.redimensionar(cantidad);

            repaint();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DialogIngresarDatos x = new DialogIngresarDatos( this, true, dispersaF1);
        x.setLocation(600, 50);
        x.setVisible(true);
        repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDispersaF1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDispersaF1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDispersaF1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDispersaF1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormDispersaF1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
